# MoveIt uses this configuration for controller management

trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.12
  execution_duration_monitoring: true

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
use_sim_time: true

moveit_simple_controller_manager:
  controller_names:
    - scara_controller
    - gripper_controller

  scara_controller:
    type: FollowJointTrajectory
    joints:
      - l1_arm_link_joint
      - l2_arm_link_joint
      - l3_arm_link_joint
      - clamp_base_link_joint
    action_ns: follow_joint_trajectory
    default: true
    use_sim_time: true

  gripper_controller:
    type: FollowJointTrajectory
    joints:
      - left_clamp_link_joint
      - right_clamp_link_joint
    action_ns: follow_joint_trajectory
    default: true
    use_sim_time: true
    
