# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    scara_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

scara_controller:
  ros__parameters:
    joints:
      - l1_arm_link_joint
      - l2_arm_link_joint
      - l3_arm_link_joint
      - clamp_base_link_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
    allow_nonzero_velocity_at_trajectory_end: true
gripper_controller:
  ros__parameters:
    joints:
      - left_clamp_link_joint
      - right_clamp_link_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
    allow_nonzero_velocity_at_trajectory_end: true